### ISSUE TITLE
觀後感以及個人建議

### ISSUE THREAD

**Issue by hungyanbin** [KenSun2018/NovelCovid19Report#1]
首先必須說沒有最正確的設計，所以如果下面的某些點你不同意也很歡迎，一起交流
整體來說你寫得很乾淨很好閱讀~~喜歡

1. bean: 所有的 Model 都是 mutable 的，通常如果是非必要我都會將每個 field 都 default 設定成  `val`，一來可以避免其他人修改到重要的值，另一方面也可以向閱讀者透漏 Model 所傳達的訊息，是期待為一個有生命周期的物件呢(可以被修改)，還是一次性物件(不能被修改)

2. package 的擺放方式，我有注意到 AdapterViewHolder 都放在同一個 package 裡了，但是 fragment 與 view model 卻不是這樣的分類方式，而是 by feature 的方式去分類，這邊如果是我的話應該會把 ViewHolder 也放在這些 feature package 裡。

3. 測試，`COVID19RxApiRepositoryTest` 感覺沒測試到甚麼東西，如果是我的話應該會把測試的精力放在"json -> model" 這邊資料的轉換，這邊測試的重點我就會放在: 紀錄當前 server 所訂的規格以及我使用第三方套件的用法是否正確

**Comment by KenSun2018** [comment]
> 首先必須說沒有最正確的設計，所以如果下面的某些點你不同意也很歡迎，一起交流
> 整體來說你寫得很乾淨很好閱讀~~喜歡
> 
> 1. bean: 所有的 Model 都是 mutable 的，通常如果是非必要我都會將每個 field 都 default 設定成  `val`，一來可以避免其他人修改到重要的值，另一方面也可以向閱讀者透漏 Model 所傳達的訊息，是期待為一個有生命周期的物件呢(可以被修改)，還是一次性物件(不能被修改)
1. 我的初衷得確是希望他就是單純的物件，不會被修改，我有查了一下知道怎麼修改了
> 2. package 的擺放方式，我有注意到 AdapterViewHolder 都放在同一個 package 裡了，但是 fragment 與 view model 卻不是這樣的分類方式，而是 by feature 的方式去分類，這邊如果是我的話應該會把 ViewHolder 也放在這些 feature package 裡。
2. 了解，因為我當時在整理viewHolder時，也有想過集在這好像怪怪的，我的分類的確是 by feature去分，晚點會移過去
> 3. 測試，`COVID19RxApiRepositoryTest` 感覺沒測試到甚麼東西，如果是我的話應該會把測試的精力放在"json -> model" 這邊資料的轉換，這邊測試的重點我就會放在: 紀錄當前 server 所訂的規格以及我使用第三方套件的用法是否正確

3. 這題我當時在寫時，也是覺得好像沒啥用，我公司沒人寫單元測試，所以我也沒太多經驗，"紀錄當前 server 所訂的規格以及我使用第三方套件的用法是否正確"，這個我會好好思考

感謝幫忙，很有幫助
