### ISSUE TITLE
隨意地看了一個 viewModel

### ISSUE THREAD

**Issue by bng86** [KenSun2018/NovelCovid19Report#2]
https://github.com/KenSun2018/NovelCovid19Report/blob/master/app/src/main/java/com/ken/android/app/novel/covid19/report/ui/map/FragmentTWMaskViewModelRxImpl.kt

1. 看到同時採用了 MutableLiveData 及 ObservableBoolean 來作為 UI 的觀察類型，不知道這樣做有什麼特別的考量嗎？
2. loading.set(false) 可以用 doFinaly 寫一個地方就好
3. CompositeDisposable 可以寫個 helper 或 extension func 來做，不用每個地方都做

**Comment by KenSun2018** [comment]
> https://github.com/KenSun2018/NovelCovid19Report/blob/master/app/src/main/java/com/ken/android/app/novel/covid19/report/ui/map/FragmentTWMaskViewModelRxImpl.kt
> 
> 1. 看到同時採用了 MutableLiveData 及 ObservableBoolean 來作為 UI 的觀察類型，不知道這樣做有什麼特別的考量嗎？
1. 純粹是因為第一次接觸 LiveData，不熟造成的，當時是因為我在寫xml databinding時，用 livedata 不會改變，今天你一提醒，我就去查了一下... 原來我的 binding 沒有設定 lifecycleOwner，用 LiveData 當然不會改變XD 等等會改掉
> 2. loading.set(false) 可以用 doFinaly 寫一個地方就好
2. 同樣是對 Rx 不熟造成，原來有這個方法
> 3. CompositeDisposable 可以寫個 helper 或 extension func 來做，不用每個地方都做
3. extension func 也是對 Kotlin 不熟，所以今天您說才知道有這個東西，有看了一些文章，要想一下該怎麼改

以上三題都是對各個 framework 不熟所造成的錯誤，感謝你指點，後面會去理解各個framework有什麼其他功能，真心感謝
